### PR TITLE
DP: VOP: DTS: adjust device tree to make VOP_Big initialized first

### PR DESCRIPTION
**Pull request by luke7r**
In this commit, we will adjust the vop node's order, to make vop_big sit as first position, so it will initialized first as crct-0, and later will always be choosed as first candidate, thus this will fix DP port right half windown show random data issue.

### CODE REVIEW

**Comment by Tonymac32** [comment]
I don't know for sure this is a deterministic solution, driver probing may not always cooperate.  To my knowledge this should be handled with overlays, the board device tree can define who gets vopb and vopl, so cases where the DP output is the 4k and HDMI is unused or 1080p, pick the appropriate overlay.

**Comment by luke7r** [comment]
It's not a deterministic solution.. or I'd even not consider it as a proper fix, just a workaround. I'm not sure if overlay will work for this, ideally, the drm subsystem should detect the crct's capability at run-time and choose resolution accordingly

**Comment by Tonymac32** [comment]
I will need to investigate, I know I've seen a construct like this used int he board level device trees, I just need to make sure that isn't for the Rockchip kernel.  The endpoints all exist in mainline, I'm just not certain disabling/enabling the configuration you want via this method actually does it.  It would be far more direct if it did.

```
&hdmi_in_vopb {
	status = "disabled";
};
```

**Comment by dsx724** [comment]
Device trees in kernel are not used.

**Pull request closed without merging**
